# Generated by Django 4.1.2 on 2022-10-17 18:56

import django.core.validators
from django.db import migrations, models
import expense_tracker.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expense_tracker.profiles.validators.only_letters_validator])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), expense_tracker.profiles.validators.only_letters_validator])),
                ('profile_image', models.URLField(blank=True, default='', null=True, validators=[expense_tracker.profiles.validators.max_file_size_validator])),
            ],
        ),
    ]
