# Generated by Django 4.1.2 on 2022-10-17 20:29

import django.core.validators
from django.db import migrations, models
import expense_tracker.profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expense_tracker.profiles.validators.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', validators=[expense_tracker.profiles.validators.max_file_size_validator]),
        ),
    ]
