# Generated by Django 4.1.2 on 2022-10-17 20:32

from django.db import migrations, models
import expense_tracker.profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_budget_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='', validators=[expense_tracker.profiles.validators.max_file_size_validator]),
        ),
    ]
