# Generated by Django 4.1.2 on 2022-10-17 20:36

from django.db import migrations, models
import expense_tracker.profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[expense_tracker.profiles.validators.max_file_size_validator]),
        ),
    ]
